baseURL: "/"
languageCode: "en-us"
title: "Openshift CI docs"
theme: "docsy"
sectionPagesMenu: "main"
contentDir: "content/en"
params:
  offlineSearch: true
  github_repo: "https://github.com/openshift/ci-docs"
enableGitInfo: true
menu:
  main:
  - name: CI Operator Reference
    url: https://steps.ci.openshift.org/ci-operator-reference
    weight: 40
  - name: Step Registry
    url: https://steps.ci.openshift.org/
    weight: 50
  - name: GitHub
    url: https://github.com/openshift/ci-tools
    weight: 60
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: "dracula"
    tabWidth: 4
