[build]
publish = "public"
command = "npm install -D --save postcss postcss-cli autoprefixer && cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.75.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.75.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.75.1"

[context.branch-deploy]
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.75.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
